from tkinter import *

window = Tk()
window.title('App 1')
topFrame = Frame(window)
bottomFrame = Frame(window)
bottomFrame_1 = Frame(bottomFrame)
bottomFrame_2 = Frame(bottomFrame)
bottomFrame_1_1 = Frame(bottomFrame_1)
bottomFrame_1_2 = Frame(bottomFrame_1)
topFrame.pack()
bottomFrame.pack()
bottomFrame_1.pack(side=LEFT)
bottomFrame_2.pack(side=LEFT)
bottomFrame_1_1.pack()
bottomFrame_1_2.pack()
text1 = Label(topFrame, text='This app demonstrate simple layout')
text2 = Label(bottomFrame_2, text='text')
button1 = Button(bottomFrame_1_1, text='Button 1', fg='green')
button2 = Button(bottomFrame_1_1, text='Button 2', fg='red')
button3 = Button(bottomFrame_1_2, text='Button 3', fg='blue')
button4 = Button(bottomFrame_1_2, text='Button 4', fg='blue')

text1.pack()
text2.pack()
button1.pack(side=LEFT)
button2.pack(side=LEFT)
button3.pack(side=LEFT)
button4.pack(side=LEFT)

window.mainloop()
